
import { useState } from 'react';
import { useToast } from '@/hooks/use-toast';
import { matchBPM, harmonicMixing } from '@/utils/audioAnalysis';
import WaveSurfer from 'wavesurfer.js';

interface AudioFeatures {
  bpm: number;
  key: string;
  energy: number;
  clarity: number;
}

interface MixSettingsType {
  bpmMatch: boolean;
  keyMatch: boolean;
  vocalLevel1: number;
  vocalLevel2: number;
  beatLevel1: number;
  beatLevel2: number;
  crossfadeLength: number;
  echo: number;
  tempo: number;
}

interface UseMixingEngineProps {
  track1Url: string | undefined;
  track2Url: string | undefined;
  track1Features: AudioFeatures | null;
  track2Features: AudioFeatures | null;
}

export const useMixingEngine = ({
  track1Url,
  track2Url,
  track1Features,
  track2Features
}: UseMixingEngineProps) => {
  // Mixing states
  const [isMixing, setIsMixing] = useState(false);
  const [mixProgress, setMixProgress] = useState(0);
  const [mixedTrackUrl, setMixedTrackUrl] = useState<string | undefined>();
  
  // Playback states
  const [isPlaying, setIsPlaying] = useState(false);
  const [volume, setVolume] = useState(0.8);
  
  // Mix settings
  const [mixSettings, setMixSettings] = useState<MixSettingsType>({
    bpmMatch: true,
    keyMatch: true,
    vocalLevel1: 0.8,
    vocalLevel2: 0.5,
    beatLevel1: 0.6,
    beatLevel2: 0.8,
    crossfadeLength: 8, // seconds
    echo: 0.2,
    tempo: 0, // -0.5 to 0.5, 0 means no change
  });
  
  const { toast } = useToast();
  
  // WaveSurfer refs
  const wavesurfer1Ref = { current: null as WaveSurfer | null };
  const wavesurfer2Ref = { current: null as WaveSurfer | null };
  const mixedWavesurferRef = { current: null as WaveSurfer | null };
  
  const updateMixSetting = (setting: keyof MixSettingsType, value: number | boolean) => {
    setMixSettings(prev => ({
      ...prev,
      [setting]: value
    }));
  };

  const updateMixSettings = (newSettings: MixSettingsType) => {
    setMixSettings(newSettings);
  };
  
  const handleMix = () => {
    if (!track1Url || !track2Url) {
      toast({
        title: "Missing tracks",
        description: "Please upload both tracks before mixing.",
        variant: "destructive",
      });
      return;
    }
    
    if (!track1Features || !track2Features) {
      toast({
        title: "Incomplete analysis",
        description: "Please wait for track analysis to complete.",
        variant: "destructive",
      });
      return;
    }
    
    setIsMixing(true);
    
    // Check if BPM matching is needed
    if (mixSettings.bpmMatch && track1Features.bpm !== track2Features.bpm) {
      console.log(`Matching BPM: ${track1Features.bpm} → ${track2Features.bpm}`);
    }
    
    // Check if keys are harmonic
    if (mixSettings.keyMatch) {
      const areHarmonic = harmonicMixing(track1Features.key, track2Features.key);
      if (!areHarmonic) {
        console.log(`Keys not harmonic: ${track1Features.key} and ${track2Features.key}`);
      }
    }
    
    // Simulate mixing process with detailed steps
    let progress = 0;
    const steps = [
      "Preparing tracks...",
      "Matching tempos...",
      "Aligning beats...",
      "Adjusting EQ levels...",
      "Applying vocal processing...",
      "Creating transitions...",
      "Finalizing mix...",
    ];
    
    let currentStep = 0;
    const interval = setInterval(() => {
      progress += 5;
      setMixProgress(progress);
      
      // Update toast with current step
      if (progress % 15 === 0 && currentStep < steps.length) {
        toast({
          title: "Mixing in progress",
          description: steps[currentStep],
        });
        currentStep++;
      }
      
      if (progress >= 100) {
        clearInterval(interval);
        setIsMixing(false);
        // In a real implementation, we would use both tracks to create a mix
        // For now, we'll simulate by using both tracks sequentially
        if (track1Url && track2Url) {
          createSimulatedMix(track1Url, track2Url);
        }
        
        toast({
          title: "Mix complete",
          description: "Your tracks have been successfully mixed!",
        });
      }
    }, 500);
  };
  
  // Simulate creating an actual mix of the two tracks
  const createSimulatedMix = (track1: string, track2: string) => {
    console.log(`Creating simulated mix of ${track1} and ${track2}`);
    console.log("Using mix settings:", mixSettings);
    
    // In a real implementation, this would create an actual mix of the two audio files
    // For this demo, we'll combine the tracks in a simple concatenation
    
    // For demo purposes, we'll set the mixed track URL
    // In a real app, this would be a new audio file generated by the backend
    setMixedTrackUrl(track1);
    
    // In a real implementation, we might do something like:
    // const combinedTrackUrl = await audioProcessingService.combineAudioTracks(
    //   track1, track2, mixSettings
    // );
    // setMixedTrackUrl(combinedTrackUrl);
  };
  
  const togglePlayback = () => {
    if (mixedWavesurferRef.current) {
      if (isPlaying) {
        mixedWavesurferRef.current.pause();
      } else {
        mixedWavesurferRef.current.play();
      }
      setIsPlaying(!isPlaying);
    }
  };
  
  const restartPlayback = () => {
    if (mixedWavesurferRef.current) {
      mixedWavesurferRef.current.seekTo(0);
    }
  };
  
  const handleTrack1WavesurferReady = (wavesurfer: WaveSurfer) => {
    wavesurfer1Ref.current = wavesurfer;
  };
  
  const handleTrack2WavesurferReady = (wavesurfer: WaveSurfer) => {
    wavesurfer2Ref.current = wavesurfer;
  };
  
  const handleMixedWavesurferReady = (wavesurfer: WaveSurfer) => {
    mixedWavesurferRef.current = wavesurfer;
    wavesurfer.setVolume(volume);
    
    wavesurfer.on('finish', () => {
      setIsPlaying(false);
    });
  };

  return {
    // State
    isMixing,
    mixProgress,
    mixedTrackUrl,
    isPlaying,
    volume,
    setVolume,
    
    // Mix settings
    mixSettings,
    updateMixSetting,
    updateMixSettings,
    
    // Methods
    handleMix,
    togglePlayback,
    restartPlayback,
    handleTrack1WavesurferReady,
    handleTrack2WavesurferReady,
    handleMixedWavesurferReady,
  };
};
